name: deploy
on:
  push:
    branches:
      - master
    paths: # 下列文件的变更触发部署，可以自行添加
      - "navigation/**"
      - ".github/workflows/deploy.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Install cloudflared
        run: wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/download/2023.3.0/cloudflared-linux-amd64

      - name: modify permission
        run: chmod 777 cloudflared

      - name: set cloudflared
        run: sudo ./cloudflared access ssh --hostname ${{ secrets.PIHOST }} --url localhost:95 &

      - name: ssh scp ssh pipelines
        uses: ilCollez/ssh-scp-deploy@v1.1.0
        with:
          host: localhost
          port: 95
          username: ${{ secrets.PIUSERNAME }}
          password: ${{ secrets.PIPASSWORD }}
          files: |
            ./pi-nginx/*
          remote-path: "/home/"
          before-upload: |
              rm -rf /home/navigation/
